apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-target
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
